[tool.ruff]
# select target rules for current project
lint.select = [
	"F",					# Pyflakes
	#"E", "W",				# pycodestyle
	#"C90",					# mccabe
	"I",					# isort
	#"N",					# pep8-naming
	#"D",					# pydocstyle
	#"UP",					# pyupgrade
	"PL",					# Pylint
]

# list rules which can be ignored
lint.ignore = ["PLR"]

# max line length
line-length = 88

# Python version
target-version = "py310"
extend-include = ["*.ipynb"]

[tool.ruff.lint.isort]
# Use a single line after each import block.
lines-after-imports = 2

[tool.ruff.format]
docstring-code-line-length = 120
docstring-code-format = true